# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nmap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nmap.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nnmap.proto\"\r\n\x0bNullRequest\"e\n\x0eStatusResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.StatusResponse.Status\"+\n\x06Status\x12\x08\n\x04INIT\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\n\n\x06\x45NDING\x10\x02\"\x1a\n\x0bScanRequest\x12\x0b\n\x03ips\x18\x01 \x03(\t\"\x1e\n\x0cScanResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\",\n\nNmapResult\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0e\n\x06report\x18\x02 \x01(\t2\x92\x01\n\x0bNmapScanner\x12\x30\n\rgetTaskStatus\x12\x0c.NullRequest\x1a\x0f.StatusResponse\"\x00\x12%\n\x04scan\x12\x0c.ScanRequest\x1a\r.ScanResponse\"\x00\x12*\n\tgetResult\x12\x0c.NullRequest\x1a\x0b.NmapResult\"\x00\x30\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STATUSRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='StatusResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENDING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=87,
  serialized_end=130,
)
_sym_db.RegisterEnumDescriptor(_STATUSRESPONSE_STATUS)


_NULLREQUEST = _descriptor.Descriptor(
  name='NullRequest',
  full_name='NullRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=27,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='StatusResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUSRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=130,
)


_SCANREQUEST = _descriptor.Descriptor(
  name='ScanRequest',
  full_name='ScanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ips', full_name='ScanRequest.ips', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=158,
)


_SCANRESPONSE = _descriptor.Descriptor(
  name='ScanResponse',
  full_name='ScanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ScanResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=190,
)


_NMAPRESULT = _descriptor.Descriptor(
  name='NmapResult',
  full_name='NmapResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='NmapResult.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='report', full_name='NmapResult.report', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=236,
)

_STATUSRESPONSE.fields_by_name['status'].enum_type = _STATUSRESPONSE_STATUS
_STATUSRESPONSE_STATUS.containing_type = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['NullRequest'] = _NULLREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['ScanRequest'] = _SCANREQUEST
DESCRIPTOR.message_types_by_name['ScanResponse'] = _SCANRESPONSE
DESCRIPTOR.message_types_by_name['NmapResult'] = _NMAPRESULT

NullRequest = _reflection.GeneratedProtocolMessageType('NullRequest', (_message.Message,), dict(
  DESCRIPTOR = _NULLREQUEST,
  __module__ = 'nmap_pb2'
  # @@protoc_insertion_point(class_scope:NullRequest)
  ))
_sym_db.RegisterMessage(NullRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSRESPONSE,
  __module__ = 'nmap_pb2'
  # @@protoc_insertion_point(class_scope:StatusResponse)
  ))
_sym_db.RegisterMessage(StatusResponse)

ScanRequest = _reflection.GeneratedProtocolMessageType('ScanRequest', (_message.Message,), dict(
  DESCRIPTOR = _SCANREQUEST,
  __module__ = 'nmap_pb2'
  # @@protoc_insertion_point(class_scope:ScanRequest)
  ))
_sym_db.RegisterMessage(ScanRequest)

ScanResponse = _reflection.GeneratedProtocolMessageType('ScanResponse', (_message.Message,), dict(
  DESCRIPTOR = _SCANRESPONSE,
  __module__ = 'nmap_pb2'
  # @@protoc_insertion_point(class_scope:ScanResponse)
  ))
_sym_db.RegisterMessage(ScanResponse)

NmapResult = _reflection.GeneratedProtocolMessageType('NmapResult', (_message.Message,), dict(
  DESCRIPTOR = _NMAPRESULT,
  __module__ = 'nmap_pb2'
  # @@protoc_insertion_point(class_scope:NmapResult)
  ))
_sym_db.RegisterMessage(NmapResult)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class NmapScannerStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getTaskStatus = channel.unary_unary(
        '/NmapScanner/getTaskStatus',
        request_serializer=NullRequest.SerializeToString,
        response_deserializer=StatusResponse.FromString,
        )
    self.scan = channel.unary_unary(
        '/NmapScanner/scan',
        request_serializer=ScanRequest.SerializeToString,
        response_deserializer=ScanResponse.FromString,
        )
    self.getResult = channel.unary_stream(
        '/NmapScanner/getResult',
        request_serializer=NullRequest.SerializeToString,
        response_deserializer=NmapResult.FromString,
        )


class NmapScannerServicer(object):

  def getTaskStatus(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def scan(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getResult(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NmapScannerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getTaskStatus': grpc.unary_unary_rpc_method_handler(
          servicer.getTaskStatus,
          request_deserializer=NullRequest.FromString,
          response_serializer=StatusResponse.SerializeToString,
      ),
      'scan': grpc.unary_unary_rpc_method_handler(
          servicer.scan,
          request_deserializer=ScanRequest.FromString,
          response_serializer=ScanResponse.SerializeToString,
      ),
      'getResult': grpc.unary_stream_rpc_method_handler(
          servicer.getResult,
          request_deserializer=NullRequest.FromString,
          response_serializer=NmapResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NmapScanner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaNmapScannerServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def getTaskStatus(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def scan(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def getResult(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaNmapScannerStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def getTaskStatus(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  getTaskStatus.future = None
  def scan(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  scan.future = None
  def getResult(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()


def beta_create_NmapScanner_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('NmapScanner', 'getResult'): NullRequest.FromString,
    ('NmapScanner', 'getTaskStatus'): NullRequest.FromString,
    ('NmapScanner', 'scan'): ScanRequest.FromString,
  }
  response_serializers = {
    ('NmapScanner', 'getResult'): NmapResult.SerializeToString,
    ('NmapScanner', 'getTaskStatus'): StatusResponse.SerializeToString,
    ('NmapScanner', 'scan'): ScanResponse.SerializeToString,
  }
  method_implementations = {
    ('NmapScanner', 'getResult'): face_utilities.unary_stream_inline(servicer.getResult),
    ('NmapScanner', 'getTaskStatus'): face_utilities.unary_unary_inline(servicer.getTaskStatus),
    ('NmapScanner', 'scan'): face_utilities.unary_unary_inline(servicer.scan),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_NmapScanner_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('NmapScanner', 'getResult'): NullRequest.SerializeToString,
    ('NmapScanner', 'getTaskStatus'): NullRequest.SerializeToString,
    ('NmapScanner', 'scan'): ScanRequest.SerializeToString,
  }
  response_deserializers = {
    ('NmapScanner', 'getResult'): NmapResult.FromString,
    ('NmapScanner', 'getTaskStatus'): StatusResponse.FromString,
    ('NmapScanner', 'scan'): ScanResponse.FromString,
  }
  cardinalities = {
    'getResult': cardinality.Cardinality.UNARY_STREAM,
    'getTaskStatus': cardinality.Cardinality.UNARY_UNARY,
    'scan': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'NmapScanner', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
